.PHONY: clean All

All:
	@echo "----------Building project:[ basic_io2 - Debug ]----------"
	@cd "basic_io2" && "$(MAKE)" -f  "basic_io2.mk" && "$(MAKE)" -f  "basic_io2.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ basic_io2 - Debug ]----------"
	@cd "basic_io2" && "$(MAKE)" -f  "basic_io2.mk" clean
