.PHONY: clean All

All:
	@echo "----------Building project:[ Uppgifter_After_Lecture - Debug ]----------"
	@cd "Uppgifter_After_Lecture" && "$(MAKE)" -f  "Uppgifter_After_Lecture.mk"
clean:
	@echo "----------Cleaning project:[ Uppgifter_After_Lecture - Debug ]----------"
	@cd "Uppgifter_After_Lecture" && "$(MAKE)" -f  "Uppgifter_After_Lecture.mk" clean
